apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-v2
spec:
  selector:
    matchLabels:
      app: app-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: app-v2
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: app
        image: asia.gcr.io/gke-nginx-test-321208/app:v2.0
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: v2
        livenessProbe:
          httpGet:
            path: /_health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "300m"